# Generated by Django 3.2.5 on 2021-08-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comhospital', '0002_auto_20210812_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='comhospital',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
