# Generated by Django 3.2.5 on 2021-07-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmapp', '0004_auto_20210728_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComHospital',
        ),
        migrations.DeleteModel(
            name='Qna',
        ),
    ]
