# Generated by Django 3.2.5 on 2021-07-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmapp', '0005_auto_20210729_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='writer',
        ),
    ]
