# Generated by Django 3.2.5 on 2021-08-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20210812_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
